status_codes = [
    ('0', 'success'),
    ('1', 'Invalid Phone Number'),
    ('2', 'otp couldn\'t be sent'),
    ('3', 'Object couldn\'t not be saved in DB'),
    ('4', 'OTP verification failed'),
    ('5', 'Invalid Request'),
    ('6', 'OTP expired'),
    ('7', 'Unable to Register user'),
    ('8', 'number already registered'),
    ('9', 'Invalid Credentials'),
    ('10', 'Contact number not verified'),
    ('11', 'Product not available'),
    ('12', 'Unable to access DB'),
    ('13', 'Kart Item not available'),
    ('14', 'Unable to delete Kart item'),
    ('15', 'Order couldn\'t be placed'),
    ('16', 'Transaction Failed'),
    ('17', 'Insufficient Funds'),
    ('18', 'Unable to update Kart'),
    ('19', 'Crop not available'),
    ('20', 'Unauthorized Access'),
    ('21', 'arguments missing')
    ('22', 'no Entry in farmer table')
]